package org.krishna.servletsdemo;

import jakarta.servlet.ServletException;

import java.io.IOException;

/*
Java Servlet technology is used to create a web application (resides at server side and generates a dynamic web page).
Servlet is a class that extends the capabilities of the servers and responds to the incoming requests. It can respond to any requests.
Servlet is a web component that is deployed on the server to create a dynamic web page.

There are many advantages of Servlet over CGI. The web container creates threads for handling the multiple requests to the Servlet.
Threads have many benefits over the Processes such as they share a common memory area, lightweight, cost of communication between the threads are low.

Website:
Website is a collection of related web pages that may contain text, images, audio and video.
Each website has specific internet address (URL) that you need to enter in your browser to access a website.
A website can be of two types
  1.Static Website  2.Dynamic Website

Static website is the basic type of website that is easy to create.
 You don't need the knowledge of web programming and database design to create a static website. Its web pages are coded in HTML.


 Dynamic Website:
 Dynamic website is a collection of dynamic web pages whose content changes dynamically.
 It accesses content from a database or Content Management System (CMS).

Dynamic website uses client-side scripting or server-side scripting, or both to generate dynamic content.

Client side scripting generates content at the client computer on the basis of user input.
The web browser downloads the web page from the server and processes the code within the page to render information to the user.

In server side scripting, the software runs on the server and processing is completed in the server then plain pages are sent to the user.


What is HTTP Request?
An HTTP request is a message sent from a client (like a web browser) to a server to ask for something. It's the foundation of data communication on the World Wide Web.
An HTTP request is a message sent by a client (like a web browser or app) to a server, asking for some resource — like a web page, file, image, or to perform an action (like submitting a form).

https://www.example.com/index.html
Components of an HTTP Request:
Request Line:
Contains the HTTP method (e.g., GET, POST), the resource being requested (e.g., /index.html), and the protocol version (e.g., HTTP/1.1).
Example: GET /index.html HTTP/1.1

Headers:
Key-value pairs providing additional information about the request.
Example: Content-Type: application/json, Authorization: Bearer token.

Body (Optional):
Contains data sent to the server (usually in POST or PUT requests).
Example: JSON payload { "username": "john", "password": "1234" }.

GET VS POST
In case of Get request, only limited amount of data can be sent because data is sent in header.
In case of post request, large amount of data can be sent because data is sent in body.

What is servlet container?
It provides the runtime environment for JavaEE (j2ee) applications.
The client/user can request only a static WebPages from the server.
 If the user wants to read the web pages as per input then the servlet container is used in java.

 Here’s what a Servlet Container does behind the scenes:
1.Receives HTTP request from a browser (like GET /home)
2.Maps URL to the correct Servlet (based on web.xml or annotations)
3.Creates or reuses the Servlet instance
4.Calls the appropriate method (doGet(), doPost())
5.Sends back the response generated by the servlet

what is servlet API?
The Servlet API is a set of classes and interfaces in the Java programming language that provides the foundation for creating and running servlets.
Servlets are server-side programs used to handle HTTP requests and generate responses dynamically, usually for web applications.

Core Concepts:

Java Servlets:
Servlets are Java classes that extend the capabilities of web servers.
They handle client requests and generate dynamic responses.
They operate within a web container (like Apache Tomcat).
Web Container:
A web container provides the runtime environment for servlets.
It manages the lifecycle of servlets, handles HTTP requests, and provides services like session management.

Servlet Container: A specialized container that executes servlets and manages their lifecycle.
Web Container: A broader term that includes a Servlet Container but also supports other Java web components like JSPs, filters, and listeners.


Key Components of the Servlet API:
1.Interfaces :The Servlet API defines several interfaces that servlets must implement:
    1.Servlet Interface: The basic interface that all servlets must implement. It defines the lifecycle methods:
                init(): Initializes the servlet.
                service(): Handles client requests.
                destroy(): Cleans up resources.
   2.HttpServletRequest: Represents the client's HTTP request and provides methods to get request parameters, headers, cookies, etc.
   3.HttpServletResponse: Represents the server's HTTP response and provides methods to set response headers, status codes, and content.
   4.ServletRequest and ServletResponse: Generic interfaces for handling client requests and responses.
   5.HttpSession: Allows session management between the client and server.

You use interfaces when:
You're defining your own classes that implement custom behavior
You want to create filters, listeners, or servlets from scratch
You want to override methods explicitly and handle all logic yourself

2.Classes:
HttpServlet Class: A convenience class that simplifies working with HTTP requests by providing methods like doGet() and doPost().
GenericServlet Class: An abstract class that implements the Servlet interface and provides basic functionality for all types of servlets (not just HTTP).
ServletContext: Provides a way for servlets within a web application to communicate with each other and share resources.
Cookie: A class to create and handle cookies.

You use classes when:
You want to build servlets quickly
You want to reuse built-in methods like doGet() and doPost()
You’re working with HTTP-based web apps

3.Annotations Modern Servlet API versions allow you to use annotations for configuration, eliminating the need for verbose XML configuration in the web.xml file.
@WebServlet: To map a servlet to a specific URL pattern.
@WebFilter: For creating filters that modify requests or responses.
@WebListener: For adding listeners to handle events like session creation or destruction.


Servlet Config:
ServletConfig is an interface in the Java Servlet API that provides configuration details to a specific servlet. It allows
 a servlet to access initialization parameters defined in the deployment descriptor (web.xml) or passed using annotations.

What is a Web-INF?
The primary purpose of the WEB-INF directory is to protect sensitive application files and house necessary configurations.

1. Security and Access Control
Inaccessible by Client: Files placed inside the WEB-INF directory (including its subdirectories) are protected.
A web client (browser) cannot directly request these files using a URL, even if the exact path is known.

Example: If a file is at .../WEB-INF/config/db.properties, a URL like http://example.com/myapp/WEB-INF/config/db.properties will result in a 404 (Not Found) or 403 (Forbidden) error.

Accessible by Server Components: Server-side components like Servlets and JSPs can access resources within WEB-INF using server-side methods (like RequestDispatcher.forward() or ServletContext.getResourceAsStream()). This allows the server to internally load configurations or delegate rendering to protected JSPs.

2. Mandatory Contents
The WEB-INF directory must contain the following core files and subdirectories for a standard Java web application:

Subdirectory/File	Purpose
web.xml	The Deployment Descriptor. This is the core configuration file that maps URLs to servlets, defines security constraints, sets initialization parameters, and lists filters and listeners. (Optional with Servlet 3.0+ and annotations, but still used for global configuration.)
classes/	Contains all the compiled Java code for the web application, including Servlets, utility classes, service layers, and application logic. These are the .class files generated from your .java source files.
lib/	Contains all the necessary JAR (Java Archive) files (third-party libraries and dependencies) required by the application. The container automatically adds these JARs to the application's classpath at runtime.


Structure of servlet execution

MyWebApp/                 --> Root directory
│── src/                  --> Source code folder
│   ├── com.example/      --> Package structure (servlet files go here)
│   │   ├── MyServlet.java
│   │   ├── AnotherServlet.java
│── web/                  --> Web-related resources
│   ├── WEB-INF/          --> Special directory for configuration and protected files
│   │   ├── web.xml       --> Deployment descriptor (optional with annotations)
│   │   ├── classes/      --> Compiled servlet classes (automatically generated)
│   │   ├── lib/          --> External libraries (JAR files)
│   ├── index.html        --> Static web page
│   ├── styles.css        --> CSS styles
│   ├── script.js         --> JavaScript files
│── pom.xml (for Maven projects) --> Dependency management
│── build.gradle (for Gradle projects) --> Dependency management

What is the Welcome-File-List in web.xml file?
Even without the url mapping  files(.html,.js) will execute when they are outside web-inf folder.

In servlets, parameters are key-value pairs used to pass data between the client and server or configure servlet behavior.

Servlets handle two main types of parameters: request parameters and initialization parameters.
 */
public class Main {
    public static void main(String[] args)
    {
        System.out.println("Welcome to servlets demo");
    }
}
